spring:
  datasource:
    url: jdbc:mysql://localhost:3306/docker_student_db
    username: root
    password: your_new_password


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6378

  cache:
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1m,recordStats

logging:
  level:
    org.hibernate.sql: DEBUG
